T10 f22 61 profile  implement delete profile on node
Zevez7/Tuiter-Project-Node pull request #19
Opened 2022-12-06 23:06 UTC by Zevez7

Postman link to test delete profile

https://api.postman.com/collections/8015820-0fd3148f-5c0f-4a0f-ab92-1a6ea0d476cd?access_key=PMAT-01GJYJ12MPKP3SGJEDGZVEPJPB

2022-12-07 10:51 UTC, hzhou74 approved these changes
postman checked. no problem

2022-12-09 06:52 UTC, ujjvalksharma requested changes
Please apply the changes and make the PR again

2022-12-09 06:52 UTC, ujjvalksharma commented on daos/ProfileDao.ts
> +   * find one profile by user id controller
PLease change js doc.

2022-12-09 06:52 UTC, ujjvalksharma commented on interfaces/ProfileDao.ts
> +   */
Please add return type.

2022-12-09 22:58 UTC, Zevez7 commented on interfaces/ProfileDao.ts
> +   */
I don't think you add return type to interface. According to Dr. Jose there's no return type for interface

2022-12-09 23:00 UTC, Zevez7 commented on daos/ProfileDao.ts
> +   * find one profile by user id controller
changed

2022-12-09 23:01 UTC, merged